name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Avoid shallow clone

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone HF repo without history (no large files)
        run: |
          git clone --depth=1 https://YoniFriedman:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Nishauri/NuruCI hf_space
  
      - name: Copy files except arv_metadata
        run: |
          rsync -av --exclude='arv_metadata/' ./ hf_space/
  
      - name: Commit and push changes
        run: |
          cd hf_space
          git add .
          git commit -m "Deploy from GitHub Actions" || echo "No changes to commit"
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/JDFPalladium/NuruHFCI.git
