name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Avoid shallow clone

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face
        run: |
          git remote add hf https://username:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Nishauri/NuruCI
          git push hf main --force
