name: Push to Hugging Face Space

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face Space
        run: |
          git remote add hf https://Nishauri:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Nishauri/NuruCI
          git push hf main --force
